# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc9f01cfe60206f95a6170b2245666f01dc580cc0601a6c624df14ed1291324936e77f42d9b65d7f9e9d6da5c925a6cc5bad36cb58ae92b7598b651170752c72

test:
  secret_key_base: c9d35b96a4cc2584d9c361fa67e90c3fb50be784ad1f79f24cc7cf2f5ccb5647b796339b75973ea13c36561d4625d44198f85bb307f2ffffa69803c3bbe2cd2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
